services:
  auth:
    volumes:
      - ../services:/app/services

  chat:
    volumes:
      - ../services:/app/services

  realtime:
    volumes:
      - ../services:/app/services

  frontend:
    volumes:
      - ../frontend-app:/app
      - messenger-node-modules:/app/node_modules
    ports:
      - "4200:4200"

  database:
    volumes:
      - ../migrations:/migrations:ro
      - messenger-db:/var/lib/postgresql
    ports:
      - "3379:5432"

  redis:
    ports:
      - "6380:6379"

volumes:
  messenger-db:
  messenger-node-modules:
