services:
  auth:
    environment:
      DATABASE_URL: "postgres://${APP_DB_USER:-messenger_user}:${APP_DB_PASSWORD:-user-password}@database:5432/messenger_test?sslmode=disable"

  chat:
    environment:
      DATABASE_URL: "postgres://${APP_DB_USER:-messenger_user}:${APP_DB_PASSWORD:-user-password}@database:5432/messenger_test?sslmode=disable"

  realtime:
    environment:
      DATABASE_URL: "postgres://${APP_DB_USER:-messenger_user}:${APP_DB_PASSWORD:-user-password}@database:5432/messenger_test?sslmode=disable"
